language: ruby
cache: bundler
rvm:
- 2.7.2
services:
  - postgresql
cache:
  bundler: true
install:
  - bundle install
script:
  - bundle exec rake db:migrate:reset RAILS_ENV=test
  - bundle exec rails webpacker:compile
  - bundle exec rails spec